---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: proton-mail-bridge-relay
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: proton-mail-bridge-relay-secret
    template:
      data:
        RELAYHOST_USERNAME: "{{ .BRIDGE_SMTP_USER }}"
        RELAYHOST_PASSWORD: "{{ .BRIDGE_SMTP_PASS }}"
  dataFrom:
    - extract:
        key: proton-mail-bridge
