---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
components:
  - ../../components/common
replacements:
  - path: ../../components/replacements/ks.yaml
resources:
  - ./arr-apps/ks.yaml
  - ./calibre-web-automated/ks.yaml
  - ./calibre-web-automated-book-downloader/ks.yaml
  - ./emby/ks.yaml
  - ./flaresolverr/ks.yaml
  - ./notifiarr/ks.yaml
  - ./overseerr/ks.yaml
  - ./plex/ks.yaml
  - ./sabnzbd/ks.yaml
#  - ./stash/ks.yaml
