---
# yaml-language-server: $schema=https://schemas.materia.wtf/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "materia-wtf-production"
spec:
  secretName: "materia-wtf-production-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "materia.wtf"
  dnsNames: ["materia.wtf", "*.materia.wtf"]
  duration: 2160h
  renewBefore: 360h
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
