---
# yaml-language-server: $schema=https://schemas.materia.wtf/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: materia-wtf
spec:
  dnsNames:
    - materia.wtf
    - "*.materia.wtf"
  duration: 160h
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  secretName: materia-wtf-tls
  usages:
    - digital signature
