---
# yaml-language-server: $schema=https://schemas.materia.wtf/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: materia-wtf-tls
spec:
  secretStoreRefs:
    - name: onepassword-connect
      kind: ClusterSecretStore
  selector:
    secret:
      name: materia-wtf-tls
  template:
    data:
      tls.crt: '{{ index . "tls.crt" | b64enc }}'
      tls.key: '{{ index . "tls.key" | b64enc }}'
  data:
    - match:
        secretKey: &key tls.crt
        remoteRef:
          remoteKey: materia-wtf-tls
          property: *key
    - match:
        secretKey: &key tls.key
        remoteRef:
          remoteKey: materia-wtf-tls
          property: *key
