---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: "${SECRET_DOMAIN/./-}-production-tls"
spec:
  secretStoreRefs:
    - name: bitwarden-secrets-manager
      kind: ClusterSecretStore
  selector:
    secret:
      name: "${SECRET_DOMAIN/./-}-production-tls"
  template:
    engineVersion: v2
    data:
      # needs to be b64enc
      tls.crt: '{{ index . "tls.crt" | b64enc }}'
      tls.key: '{{ index . "tls.key" | b64enc }}'
  data:
    - match:
        remoteRef:
          remoteKey: lets_encrypt_tls
