---
# yaml-language-server: $schema=https://schemas.materia.wtf/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: "materia-wtf-production-tls"
spec:
  secretStoreRefs:
    - name: bitwarden-secrets-manager
      kind: ClusterSecretStore
  selector:
    secret:
      name: "materia-wtf-production-tls"
  data:
    - match:
        secretKey: tls.crt
        remoteRef:
          remoteKey: lets_encrypt_tls_crt
    - match:
        secretKey: tls.key
        remoteRef:
          remoteKey: lets_encrypt_tls_key
