[worldserver]

########################################
# mod-accountbound
########################################

# Allow gamemasters to save/load companions and mounts.
AccountBound.Gamemasters = 0

# Share companions (non-combat pets) across all characters of an account.
AccountBound.Companions = 1

# Share heirlooms across the account. Requires the module's vendor creature to
# be spawned first, so left off until that NPC exists.
AccountBound.Heirlooms = 0

# Share mounts across all characters of an account.
AccountBound.Mounts = 1
