---
# yaml-language-server: $schema=https://schemas.tholinka.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "${APP}-${PVC_NAME}-volsync-b2"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: "${APP}-${PVC_NAME}-volsync-b2-secret"
    template:
      data:
        # AWS_S3_ENDPOINT: '{{ .AWS_S3_ENDPOINT }}'
        # KOPIA_REPOSITORY: '{{ .REPOSITORY_TEMPLATE }}'
        # KOPIA_PASSWORD: '{{ .KOPIA_PASSWORD }}'
        RESTIC_REPOSITORY: '{{ .REPOSITORY_TEMPLATE }}'
        RESTIC_PASSWORD: '{{ .RESTIC_PASSWORD }}'
        AWS_ACCESS_KEY_ID: '{{ .AWS_ACCESS_KEY_ID }}'
        AWS_SECRET_ACCESS_KEY: '{{ .AWS_SECRET_ACCESS_KEY }}'
  dataFrom:
    - extract:
        key: volsync_s3_template
