---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: actions-runner-controller
  namespace: actions-runner-system
spec:
  path: ./kubernetes/apps/actions-runner-system/actions-runner-controller/app
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 1h
  prune: true
  wait: true
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: actions-runner-controller-runners
  namespace: actions-runner-system
spec:
  components:
    - ../../../../components/common
  path: ./kubernetes/apps/actions-runner-system/actions-runner-controller/runners
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 1h
  prune: true
  wait: false
  dependsOn:
    - name: actions-runner-controller
    - name: longhorn
      namespace: storage
