---
# yaml-language-server: $schema=https://version-2026-5.goauthentik.io/blueprints/v1/schema.json
version: 1
metadata:
  name: Materia - Flow Bindings - Invalidation
entries:
  - id: binding_invalidation_logout
    model: authentik_flows.flowstagebinding
    identifiers:
      target: !Find [authentik_flows.flow, [slug, "materia-invalidation"]]
      stage: !Find [authentik_stages_user_logout.userlogoutstage, [name, "materia-session-invalidation"]]
    attrs:
      order: 10
      policy_engine_mode: all  # all([]) = True → always run when no policies
