---
# yaml-language-server: $schema=https://version-2026-5.goauthentik.io/blueprints/v1/schema.json
version: 1
metadata:
  name: Materia - Flow Bindings - Enrollment
entries:
  - id: binding_enrollment_invitation
    model: authentik_flows.flowstagebinding
    identifiers:
      target: !Find [authentik_flows.flow, [slug, "materia-enrollment-invitation"]]
      stage: !Find [authentik_stages_invitation.invitationstage, [name, "materia-enrollment-invitation"]]
    attrs:
      order: 10
      policy_engine_mode: all  # all([]) = True → always run when no policies

  - id: binding_enrollment_prompt
    model: authentik_flows.flowstagebinding
    identifiers:
      target: !Find [authentik_flows.flow, [slug, "materia-enrollment-invitation"]]
      stage: !Find [authentik_stages_prompt.promptstage, [name, "materia-enrollment-prompt"]]
    attrs:
      order: 20
      policy_engine_mode: all  # all([]) = True → always run when no policies

  - id: binding_enrollment_user_write
    model: authentik_flows.flowstagebinding
    identifiers:
      target: !Find [authentik_flows.flow, [slug, "materia-enrollment-invitation"]]
      stage: !Find [authentik_stages_user_write.userwritestage, [name, "materia-enrollment-user-write"]]
    attrs:
      order: 30
      policy_engine_mode: all  # all([]) = True → always run when no policies

  - id: binding_enrollment_email_verification
    model: authentik_flows.flowstagebinding
    identifiers:
      target: !Find [authentik_flows.flow, [slug, "materia-enrollment-invitation"]]
      stage: !Find [authentik_stages_email.emailstage, [name, "materia-enrollment-email-verification"]]
    attrs:
      order: 40
      policy_engine_mode: all  # all([]) = True → always run when no policies

  - id: binding_enrollment_login
    model: authentik_flows.flowstagebinding
    identifiers:
      target: !Find [authentik_flows.flow, [slug, "materia-enrollment-invitation"]]
      stage: !Find [authentik_stages_user_login.userloginstage, [name, "materia-authentication-login"]]
    attrs:
      order: 100
      policy_engine_mode: all  # all([]) = True → always run when no policies
