---
# yaml-language-server: $schema=https://version-2026-5.goauthentik.io/blueprints/v1/schema.json
version: 1
metadata:
  name: Materia - Flow Bindings - Passwordless
entries:
  - id: binding_passwordless_identification
    model: authentik_flows.flowstagebinding
    identifiers:
      target: !Find [authentik_flows.flow, [slug, "materia-passwordless-authentication"]]
      stage: !Find [authentik_stages_identification.identificationstage, [name, "materia-passwordless-identification"]]
    attrs:
      order: 10

  - id: binding_passwordless_webauthn
    model: authentik_flows.flowstagebinding
    identifiers:
      target: !Find [authentik_flows.flow, [slug, "materia-passwordless-authentication"]]
      stage: !Find [authentik_stages_authenticator_validate.authenticatorvalidatestage, [name, "materia-passwordless-mfa-validation"]]
    attrs:
      order: 20

  - id: binding_passwordless_login
    model: authentik_flows.flowstagebinding
    identifiers:
      target: !Find [authentik_flows.flow, [slug, "materia-passwordless-authentication"]]
      stage: !Find [authentik_stages_user_login.userloginstage, [name, "materia-authentication-login"]]
    attrs:
      order: 100
