---
# yaml-language-server: $schema=https://version-2026-5.goauthentik.io/blueprints/v1/schema.json
version: 1
metadata:
  name: Embedded Outpost
entries:
  - id: embedded_outpost
    model: authentik_outposts.outpost
    identifiers:
      name: authentik Embedded Outpost
    attrs:
      type: proxy
      providers:
        # Media apps
        - !Find [authentik_providers_proxy.proxyprovider, [name, "radarr"]]
        - !Find [authentik_providers_proxy.proxyprovider, [name, "radarr 4k"]]
        - !Find [authentik_providers_proxy.proxyprovider, [name, "radarr anime"]]
        - !Find [authentik_providers_proxy.proxyprovider, [name, "sonarr"]]
        - !Find [authentik_providers_proxy.proxyprovider, [name, "sonarr anime"]]
        - !Find [authentik_providers_proxy.proxyprovider, [name, "prowlarr"]]
        - !Find [authentik_providers_proxy.proxyprovider, [name, "lidarr"]]
        - !Find [authentik_providers_proxy.proxyprovider, [name, "bazarr"]]
        - !Find [authentik_providers_proxy.proxyprovider, [name, "bazarr anime"]]
        - !Find [authentik_providers_proxy.proxyprovider, [name, "sabnzbd"]]
        - !Find [authentik_providers_proxy.proxyprovider, [name, "qbittorrent"]]
        - !Find [authentik_providers_proxy.proxyprovider, [name, "autobrr"]]
        - !Find [authentik_providers_proxy.proxyprovider, [name, "notifiarr"]]
        - !Find [authentik_providers_proxy.proxyprovider, [name, "stash"]]
        - !Find [authentik_providers_proxy.proxyprovider, [name, "calibre"]]
        - !Find [authentik_providers_proxy.proxyprovider, [name, "calibre downloader"]]
        - !Find [authentik_providers_proxy.proxyprovider, [name, "readarr"]]
        # Admin apps
        - !Find [authentik_providers_proxy.proxyprovider, [name, "victoriametrics"]]
        - !Find [authentik_providers_proxy.proxyprovider, [name, "vmalert"]]
        - !Find [authentik_providers_proxy.proxyprovider, [name, "alertmanager"]]
        - !Find [authentik_providers_proxy.proxyprovider, [name, "status"]]
        - !Find [authentik_providers_proxy.proxyprovider, [name, "flux"]]
        - !Find [authentik_providers_proxy.proxyprovider, [name, "proxmox"]]
        - !Find [authentik_providers_proxy.proxyprovider, [name, "pi-hole (0)"]]
        - !Find [authentik_providers_proxy.proxyprovider, [name, "pi-hole (1)"]]
      config:
        authentik_host: https://auth.materia.wtf
        authentik_host_insecure: false
        log_level: info
        object_naming_template: "ak-outpost-%(name)s"
        kubernetes_replicas: 1
        kubernetes_namespace: security
        kubernetes_service_type: ClusterIP
        kubernetes_disabled_components: []
        kubernetes_image_pull_secrets: []
        kubernetes_ingress_annotations: {}
