---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-webhook-token
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  refreshInterval: 1m
  target:
    name: github-webhook-token-secret
  data:
    - secretKey: token
      remoteRef:
        key: "9df91a1d-df45-4bdf-ad57-b36900231f8c"
