---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: home-ops-runner
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  refreshInterval: 5m
  target:
    name: home-ops-runner-secret
  data:
    - secretKey: github_app_id
      remoteRef:
        key: "276dbc22-f122-4217-86b1-b23100652ab7"
    - secretKey: github_app_installation_id
      remoteRef:
        key: "14c33b01-8417-4c10-af68-b37c0175f94e"
    - secretKey: github_app_private_key
      remoteRef:
        key: "ab613d67-e1a9-4900-a74a-b231006508c1"
