---
# yaml-language-server: $schema=https://schemas.materia.wtf/monitoring.coreos.com/servicemonitor_v1.json
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: azerothcore-db
spec:
  endpoints:
    - port: metrics
      path: /metrics
  jobLabel: app.kubernetes.io/name
  namespaceSelector:
    matchNames:
      - games
  selector:
    matchLabels:
      app.kubernetes.io/instance: azerothcore-db
      app.kubernetes.io/name: azerothcore-db
