---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./prometheusrule.yaml
  - ./externalsecret-blueprints.yaml
  - ./grafanadashboard.yaml
  - ./helmrelease.yaml
  - ./httproute.yaml
  - ./ocirepository.yaml
  - ./referencegrant.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: authentik-blueprints
    files:
      - ./blueprints/01-groups.yaml
      - ./blueprints/02-users.yaml
      - ./blueprints/03-policies.yaml
      - ./blueprints/04-scopes.yaml
      - ./blueprints/05-flows.yaml
      - ./blueprints/06-sources.yaml
      - ./blueprints/07-stages.yaml
      - ./blueprints/08-bindings-authentication.yaml
      - ./blueprints/09-bindings-enrollment.yaml
      - ./blueprints/10-bindings-invalidation.yaml
      - ./blueprints/11-bindings-passwordless.yaml
      - ./blueprints/12-bindings-recovery.yaml
      - ./blueprints/13-bindings-user-settings.yaml
      - ./blueprints/14-branding.yaml
      - ./blueprints/15-apps-oidc.yaml
      - ./blueprints/16-apps-proxy-media.yaml
      - ./blueprints/17-apps-proxy-admin.yaml
      - ./blueprints/18-outpost.yaml
