---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: radarr-4k-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: radarr-4k-secret
  data:
    - secretKey: RADARR__AUTH__APIKEY
      remoteRef:
        key: "ec12ac6b-6606-427a-be31-ae6e03261c0b"
