---
# yaml-language-server: $schema=https://schemas.materia.wtf/external-secrets.io/externalsecret_v1.json
# this secret gets manually created at bootstrap, and then this takes control of it
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bitwarden-access-token
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  refreshInterval: 1m
  target:
    name: bitwarden-access-token-secret
  # this can NOT end in a newline or it doesn't work
  data:
    - secretKey: token
      remoteRef:
        key: bitwarden_auth_token_rw
---
# yaml-language-server: $schema=https://schemas.materia.wtf/external-secrets.io/externalsecret_v1.json
# bootstrap seed creates this initially; this takes over once ESO is running
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bitwarden-config
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  refreshInterval: 1h
  target:
    name: bitwarden-config
  data:
    - secretKey: BITWARDEN_ORGANIZATION_ID
      remoteRef:
        key: bitwarden_org_id
    - secretKey: BITWARDEN_PROJECT_ID
      remoteRef:
        key: bitwarden_project_id
