---
# yaml-language-server: $schema=https://schemas.materia.wtf/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: calibre
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: calibre-secret
    template:
      data:
        HARDCOVER_TOKEN: "{{ .hardcover-api-key }}"
  dataFrom:
    - extract:
        key: calibre
