---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-cleanup-operator
spec:
  chart:
    spec:
      chart: kube-cleanup-operator
      version: 1.0.4
      sourceRef:
        kind: HelmRepository
        name: lwolf-charts
        namespace: system-controllers
      interval: 15m
  interval: 15m
  values:
    securityContext:
      runAsUser: 65534 # run as nobody user
    containerSecurityContext:
      runAsUser: 65534
      runAsNonRoot: true
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
    rbac:
      create: true
      global: true
    args:
      - --delete-failed-after=0
      - --delete-successful-after=0
      - --delete-pending-pods-after=3m
      - --delete-evicted-pods-after=3m
      - --delete-orphaned-pods-after=3m
      - --legacy-mode=false
