---
# yaml-language-server: $schema=https://schemas.materia.wtf/postgresql.cnpg.io/pooler_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: postgres-${APP}-pooler
spec:
  cluster:
    name: postgres-${APP}
  instances: 2
  type: rw
  pgbouncer:
    poolMode: session
    parameters:
      max_client_conn: "200"
      default_pool_size: "25"
      server_login_retry: "1"
  monitoring:
    enablePodMonitor: true
