---
# yaml-language-server: $schema=https://schemas.materia.wtf/postgresql.cnpg.io/pooler_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: postgres-${APP}-pooler
spec:
  cluster:
    name: postgres-${APP}
  instances: 2
  type: rw
  pgbouncer:
    poolMode: transaction
    authQuerySecret:
      name: postgres-${APP}-superuser
    authQuery: "SELECT usename, passwd FROM pg_shadow WHERE usename=$1"
    parameters:
      max_client_conn: "200"
      default_pool_size: "25"
  monitoring:
    enablePodMonitor: true
