---
# yaml-language-server: $schema=https://schemas.materia.wtf/external-secrets.io/externalsecret_v1.json
# manages the domain-config secret in flux-system used by Flux for postBuild substitution
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: domain-config
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: domain-config
  data:
    - secretKey: SECRET_DOMAIN
      remoteRef:
        key: SECRET_DOMAIN
