---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: bitwarden-secrets-manager
spec:
  provider:
    bitwardensecretsmanager:
      apiURL: https://api.bitwarden.com
      identityURL: https://identity.bitwarden.com
      bitwardenServerSDKURL: https://bitwarden-sdk-server.security.svc.cluster.local:9998
      organizationID: ${BITWARDEN_ORGANIZATION_ID}
      projectID: ${BITWARDEN_PROJECT_ID}
      auth:
        secretRef:
          credentials:
            key: token
            name: bitwarden-access-token
            namespace: &namespace security
      caProvider:
        type: Secret
        name: bitwarden-css-certs
        namespace: *namespace
        key: ca.crt
