---
# yaml-language-server: $schema=https://flux.tholinka.dev/helmrelease/v2/github/external-secrets/external-secrets/main/deploy/charts/external-secrets
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
spec:
  chartRef:
    kind: OCIRepository
    name: external-secrets
  interval: 1h
  values:
    bitwarden-sdk-server:
      enabled: true
      podAnnotations:
        secret.reloader.stakater.com/reload: "bitwarden-css-certs,bitwarden-tls-certs,bitwarden-secrets-manager,bitwarden-access-token-secret"
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          memory: 256Mi
    grafanaDashboard:
      enabled: true
    leaderElect: true
    serviceMonitor:
      enabled: true
    webhook:
      replicaCount: 2
