---
# Base self signed issuer for the bootstrap certificate
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: bitwarden-bootstrap-issuer
  namespace: security
spec:
  selfSigned: {}
---
# Self-signed certificate for the Bitwarden certificate issuer
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bitwarden-bootstrap-certificate
  namespace: security
spec:
  isCA: true
  secretName: bitwarden-bootstrap-certs
  subject:
    organizations:
      - external-secrets.io
  dnsNames:
    - security-bitwarden-sdk-server.security.svc.cluster.local
    - bitwarden-sdk-server.security.svc.cluster.local
    - bitwarden-sdk-server.security
    - bitwarden-sdk-server
    - localhost
  ipAddresses:
    - 127.0.0.1
    - ::1
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 2048
    rotationPolicy: Always
  issuerRef:
    name: bitwarden-bootstrap-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
# ClusterIssuer for Bitwarden using the self-signed certificate
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: bitwarden-certificate-issuer
spec:
  ca:
    secretName: bitwarden-bootstrap-certs
