---
# yaml-language-server: $schema=https://schemas.tholinka.dev/external-secrets.io/externalsecret_v1.json
# this secret gets manually created at bootstrap, and then this takes control of it
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cluster-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: cluster-secrets
    template:
      templateFrom:
        - target: Data
          literal: |-
            {{ .CLUSTER_SECRETS }}
  data:
    - secretKey: CLUSTER_SECRETS
      remoteRef:
        key: cluster_secrets
