---
apiVersion: v1
kind: Namespace
metadata:
  name: not-used
  labels:
    app.kubernetes.io/name: not-used
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
    volsync.backube/privileged-movers: "true"
