---
# yaml-language-server: $schema=https://schemas.materia.wtf/external-secrets.io/externalsecret_v1.json
# bootstrap seed creates this initially; this takes over once ESO is running
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bitwarden-config
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  refreshInterval: 1h
  target:
    name: bitwarden-config
  data:
    - secretKey: BITWARDEN_ORGANIZATION_ID
      remoteRef:
        key: bitwarden_org_id
    - secretKey: BITWARDEN_PROJECT_ID
      remoteRef:
        key: bitwarden_project_id
