---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-instance
spec:
  path: ./kubernetes/apps/flux-system/flux-instance/app
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  dependsOn:
    - name: flux-operator
  interval: 1h
  prune: true
  targetNamespace: flux-system
  wait: false
