---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
spec:
  chartRef:
    kind: OCIRepository
    name: longhorn
  interval: 1h
  values:
    monitoring:
      enabled: true
      createPrometheusRules: true
    defaultSettings:
      defaultReplicaCount: "2"
      # Overprovisioning might be needed when using volsync
      storageOverProvisioningPercentage: "1000"
      storageReservedPercentageForDefaultDisk: "10"
      storageMinimalAvailablePercentage: "1"
      orphanAutoDeletion: true
      concurrentAutomaticEngineUpgradePerNodeLimit: "2"
      # -- Maximum number of replicas that can be concurrently rebuilt on each node.
      concurrentReplicaRebuildPerNodeLimit: "1"
      replicaReplenishmentWaitInterval: "15"
      defaultLonghornStaticStorageClass: longhorn
      nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
      # -- Setting that allows you to specify the data engine version for the default Longhorn StorageClass. (Options: "v1", "v2")
      dataEngine: v2
      defaultDataPath: /var/mnt/longhorn-data
    persistence:
      # Set to false to pick another CSI as default
      defaultClass: true
      dataEngine: v2
      # Increase to 3 for a multi-node cluster
      defaultClassReplicaCount: "2"
