---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-snapshot-sc
allowVolumeExpansion: true
provisioner: driver.longhorn.io
parameters:
  # used for volsync to copy from.
  # we set this to 1 replica for faster restores from the snapclass
  dataLocality: disabled
  numberOfReplicas: "1"
  replicaAutoBalance: best-effort
  staleReplicaTimeout: "30"
reclaimPolicy: Delete
deletionPolicy: Delete
volumeBindingMode: Immediate
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-cache-sc
allowVolumeExpansion: true
provisioner: driver.longhorn.io
parameters:
  # we set this to 2 replica for less copies of the cache, which can be blown away safely.
  dataLocality: disabled
  numberOfReplicas: "2"
  replicaAutoBalance: best-effort
  staleReplicaTimeout: "30"
reclaimPolicy: Delete
volumeBindingMode: Immediate
