---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app autobrr
  namespace: torrents
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/volsync
  path: ./kubernetes/apps/torrents/autobrr/app
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 30m
  retryInterval: 5m
  wait: false
  prune: true
  timeout: 5m
  dependsOn:
    - name: storage-ready
      namespace: flux-system
  postBuild:
    substitute:
      APP: *app
      PVC_NAME: config
      GATUS_SUBDOMAIN: autobrr
      PVC_CAPACITY: 10Gi
      VOLSYNC_CAPACITY: 10Gi
      VOLSYNC_SCHEDULE: ${AUTOBRR_CONFIG_VOLSYNC_SCHEDULE}
