---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: crd-schema-publisher
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: crd-schema-publisher-secret
    template:
      data:
        CLOUDFLARE_API_TOKEN: "{{ .CLOUDFLARE_API_TOKEN }}"
        CLOUDFLARE_ACCOUNT_ID: "{{ .CLOUDFLARE_ACCOUNT_ID }}"
  dataFrom:
    - extract:
        key: cloudflare_k8s_schemas
