---
# yaml-language-server: $schema=https://schemas.materia.wtf/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: crd-schema-publisher
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: crd-schema-publisher-secret
    template:
      data:
        CLOUDFLARE_API_TOKEN: "{{ .CLOUDFLARE_SCHEMAS_API_TOKEN }}"
        CLOUDFLARE_ACCOUNT_ID: "{{ .CLOUDFLARE_ACCOUNT_ID }}"
  dataFrom:
    - extract:
        key: cloudflare
