---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app calibre-web-automated
  namespace: media
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/volsync
  path: ./kubernetes/apps/media/calibre-web-automated/app
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 30m
  retryInterval: 5m
  prune: true
  timeout: 5m
  wait: true
  postBuild:
    substitute:
      APP: *app
      PVC_NAME: config
      PVC_CAPACITY: 100Gi
      VOLSYNC_CAPACITY: 100Gi
      VOLSYNC_SCHEDULE: ${CALIBRE_WEB_CONFIG_VOLSYNC_SCHEDULE}
