---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: system-controllers
components:
  - ../../components/alerts
  - ../../components/common
replacements:
  - path: ../../components/replacements/ks.yaml
resources:
  - ./k8tz/ks.yaml
  - ./kube-cleanup-operator/ks.yaml
  - ./node-feature-discovery/ks.yaml
  - ./snapshot-controller/ks.yaml
