---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: torrents
components:
  - ../../components/common
replacements:
  - path: ../../components/replacements/ks.yaml
resources:
 - ./autobrr/ks.yaml
 - ./cross-seed/ks.yaml
 - ./qbitmanage/ks.yaml
 - ./qbittorrent/ks.yaml
  - ./qui/ks.yaml
