---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: network
components:
  - ../../components/common
replacements:
  - path: ../../components/replacements/ks.yaml
resources:
  - ./certificates/ks.yaml
  - ./cloudflare-tunnel/ks.yaml
  - ./dnscrypt-proxy/ks.yaml
  - ./envoy-gateway/ks.yaml
  - ./external-dns/ks.yaml
  - ./k8s-gateway/ks.yaml
  - ./multus/ks.yaml
  # - ./pihole/ks.yaml
