---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: truenas-gui
  namespace: network
  labels:
    kubernetes.io/service-name: truenas-gui
addressType: IPv4
endpoints:
  - addresses:
      - "${TRUENAS_IP:=192.168.20.22}"
ports:
  - port: 443
    name: https
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: truenas-gui
  namespace: network
spec:
  type: ClusterIP
  clusterIP: None # Headless service for the EndpointSlice
  ports:
    - port: 443
      targetPort: 443
      name: https
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: truenas-tls
  namespace: network
  annotations:
    external-dns.alpha.kubernetes.io/target: "internal.${SECRET_DOMAIN:=flux.local}"
spec:
  parentRefs:
    - name: envoy-internal
      namespace: network
      sectionName: https
  hostnames:
    - "nas.${SECRET_DOMAIN:=flux.local}"
  rules:
    - backendRefs:
        - name: truenas-gui
          port: 443
