---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: internal-garage
  namespace: network
  labels:
    kubernetes.io/service-name: internal-garage
addressType: IPv4
endpoints:
  - addresses:
      - "${TRUENAS_IP:=192.168.20.22}"
ports:
  - port: 30186
    name: https
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: internal-garage
  namespace: network
spec:
  type: ClusterIP
  clusterIP: None # Headless service for the EndpointSlice
  ports:
    - port: 30186
      targetPort: 30186
      name: https
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: external-service-tlsroute-garage
  namespace: network
  annotations:
    external-dns.alpha.kubernetes.io/target: "internal-tls.${SECRET_DOMAIN:=flux.local}"
spec:
  parentRefs:
    - name: envoy-internal-tls
      namespace: network
      sectionName: tls
  hostnames:
    - "garage.${SECRET_DOMAIN:=flux.local}"
  rules:
    - backendRefs:
        - name: internal-garage
          port: 30186
